# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#cronjob-v1beta1-batch

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: minimal-cron-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  suspend: false
  jobTemplate:
    spec:
      completions: 3
      parallelism: 1
      backoffLimit: 10
      template:
        spec:
          containers:
            - name: centos-container
              image: centos:7
              command: ["/bin/sh", "-c"]
              args:
                - date +"%N" | cut -c 7 | egrep "[1|3|5|7|9]"
          restartPolicy: OnFailure
