# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#job-v1-batch

apiVersion: batch/v1
kind: Job
metadata:
  name: minimal-job
spec:
  completions: 3
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: centos-container
          image: centos:7
          command: ["/bin/sh", "-c"]
          args:
            - date +"%N" | cut -c 7 | egrep "[1|3|5|7|9]"
      restartPolicy: OnFailure
