# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#pod-v1-core

apiVersion: v1
kind: Pod
metadata:
  name: minimal-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1-alpine
