apiVersion: v1
kind: Pod
metadata:
  name: sleeper
spec:
  containers:
    - name: centos
      image: centos
      command: ["/bin/bash", "-c"]
      args: ["trap : TERM INT; sleep infinity & wait"]
