# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#deployment-v1-apps

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-label
  template:
    metadata:
      labels:
        app: app-label
    spec:
      containers:
        - name: nginx-container
          image: nginx:1-alpine
          ports:
            - containerPort: 80
