# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#service-v1-core

apiVersion: v1
kind: Service
metadata:
  name: minimal-node-port
spec:
  type: NodePort
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
  selector:
    app: app-label
